### ISSUE TITLE
Voorzien van een "Sighting" model

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#1]
We moeten bepalen wat een sighting precies inhoud. Volgende velden zijn noodzakelijk:
- Title: Vat kort en bondig samen wat er werd gezien (nodig voor het zoeken)
- Date: Wanneer vond de sighting plaats
- Author: Wie rapporteert de sighting -> **automatisch bepaald!**
- Longitude: Coördinaat nodig voor google maps en weer
- Latitude: Coördinaat nodig voor google maps en weer
- URL: Verwijst naar een afbeelding die we dan kunnen tonen
- Comments: Bijhouden van welke comments er bij deze post horen

**Comment by YoussefBoudiba** [comment]
Ok, zal ik doen. Ik ga ook misschien nog een model maken voor comments.
