### ISSUE TITLE
Nette/gestructureerde code

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#10]
Hoewel het niet het belangrijkste is moeten we toch wel rekening houden met het ordelijk houden van de code: code duplicatie, code die conceptueel ergens anders moet staan, ...

Wanneer de requirements afgewerkt zijn moeten we zeker de code eens nagaan om te zien wat we beter kunnen doen.

**Comment by YoussefBoudiba** [comment]
Ik laat dit aan jullie over, ik heb heel wat tijd in het project gestoken en ik wil me hiermee niet bezig houden..

**Comment by YoussefBoudiba** [comment]
Hiernaast ook checken dat er altijd gecontroleerd wordt op user input en misschien de forms robuuster maken. Nogmaals ik zal me hier niet mee bezig houden. @clone1612 Nu dat edit af is (jullie kunnen de code makkelijk wijzigen om meer info te wijzigen) kan ik er van uitgaan dat mijn werk af is?
ps: De webapp mooier maken (css/foto's/music/animatie/...) mag altijd ;)

**Comment by jhemelhof** [comment]
Uw werk is inderdaad af, was al hiermee bezig ;)

**Comment by YoussefBoudiba** [comment]
De error van invalid username, username already taken zijn weg. Waarom heb je ze er uit gehaald? De html checkup is goed, ma er moet wel een error zijn als de username al bestaat of juist niet bestaat.

**Comment by jhemelhof** [comment]
Oeps, iets te veel willen cleanen en die error uit het oog verloren. Fix komt eraan

**Comment by YoussefBoudiba** [comment]
Nu werkt de app met "echte" datum. Het wordt wel in een specifiek formaat weergegeven ma het werkt :p En nieuwe sightings worden eerst weergegeven :)

**Comment by YoussefBoudiba** [comment]
@gogobetto kan je de de sighting pagina "mooier" maken? Dus zowel sighting als de comments die erbij horen. En hoe ver zit je met edit user?

**Comment by jhemelhof** [comment]
Netjes! Denk je nog aan iets dat je verandert wilt zien?

**Comment by YoussefBoudiba** [comment]
De sighting pagina en bijhorend comment section ziet er wat slordig uit, ma dat is enkel stylen. Idem voor home page (dus de foto naast de login/signup (local mag trouwens weg) en niet er just boven). Euhm de search misschien, werkt dat ook voor users (dus user profiel of pagina gaan opzoeken)?

**Comment by jhemelhof** [comment]
Searchen kan op dit moment ook op username, die geeft dan alle sightings van die user. Maar profiel bezoeken nog niet, ben er wel mee bezig :)

**Comment by YoussefBoudiba** [comment]
en ook , de search pagina is nogal empty, enig idee om dat op te vullen?

**Comment by jhemelhof** [comment]
Als ik de search in de navbar aan de praat krijg zal die pagina enkel te zien zijn met resultaten, dan is dat sowieso opgelost.

**Comment by YoussefBoudiba** [comment]
:+1:

**Comment by jhemelhof** [comment]
Search is nu volledig af: zoeken via de zoekbalk op author, title, description, etc. brengt je naar een pagina met zoekresultaten. Hier kan je dan besluiten om de sighting zelf te bekijken, **View Sighting**, oftewel de profielpagina van de author te bekijken, **View Author Profile**.

Als er aan de search nog iets ontbreekt/niet werkt zeg het dan gerust.

**Comment by YoussefBoudiba** [comment]
aan de search ontbreekt er niets, kan je html5 validators toevoegen aan de post sighting form? + Zijn er restricties aan username en password?

**Comment by YoussefBoudiba** [comment]
Er ontbreken nog foutmeldingen bij de login page. username does not exist etc. Kan je ze allemaal terug zetten aub 
Gebruik de html5validator enkel bij het posten van comments en nieuwe sighting (ook editen). de login page en signup had ik liever hoe het toen was (zeer robuust tegenover nu).

**Comment by YoussefBoudiba** [comment]
@clone1612  kan je een default foto voorzien (niet te groot niet te klein en niets fancy) als de user geen foto heeft meegegeven?

**Comment by jhemelhof** [comment]
Komt in orde

**Comment by YoussefBoudiba** [comment]
:+1:

**Comment by jhemelhof** [comment]
Default foto staat erop

**Comment by YoussefBoudiba** [comment]
Mooi! Kan je het posten van nieuwe sightings robuuster maken met html5 validators? De login en signup zitten er goed uit trouwens!

**Comment by jhemelhof** [comment]
Er lijkt iets mis te zijn met de combinatie validator + nieuwe sighting want normaal waren de validators al actief. Ik onderzoek het :)

**Comment by YoussefBoudiba** [comment]
Bedankt! Ik ga nu op zoek naar een html5 template om het allemaal mooier te maken. Euhm ook alle functionaliteiten blijven testen om zeker te zijn dat alles werkt en dat er geen bugs zijn. En nog, zie je het zitten om morgen op de vub de demo voor te bereiden en no de presentatie te bespreken (roberto is hiermee bezig)

**Comment by jhemelhof** [comment]
Heb wel les tot 13u dus indien het voor jullie past tussen 13 - 14u om voor te bereiden?

**Comment by YoussefBoudiba** [comment]
ok voor 13u

**Comment by jhemelhof** [comment]
New Sighting zou nu ook validators moeten hebben, het werkt toch bij mij :)

**Comment by YoussefBoudiba** [comment]
Ik heb de css wat bijgewerkt

**Comment by jhemelhof** [comment]
Ziet er goed uit :+1: Heb ook de bug met preview adres opgelost (waar hij geen rekening hield met eventuele coördinaten)

**Comment by gogobetto** [comment]
Heel mooi gedaan !

**Comment by gogobetto** [comment]
Wat er op de presantite zeker moet getoont worden:
- how to register
- overview of their account details.(+you can edit them)
- view, search, create and modify the information
- social aspect (comments)

Ik stel voor dat jannick kleine intro doet, daarna beginne we de demo youssef geeft wat technische info en ik doe wat real-time demo (wie brengt zijn laptop mee?) tot straks (13h?) en ik zorg ook nog voor een kleine ppt

**Comment by gogobetto** [comment]
Wat zijn de used technologies, architecture and web services da we gebruiken, zodat ik niks vergeet
