### ISSUE TITLE
Verslag schrijven

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#13]
In het verslag moeten we gewoon uitleggen hoe we elke requirement hebben geïmplementeerd. Ik stel voor dat we ze verdelen.
- [x] Inleiding voor het rapport (**Roberto**)
- [x] Design van de app (**Jannick**)
- [x] User kan zich registreren/inloggen (Youssef)
- [x] User heeft een profiel (**Roberto**)
- [x] User kan dingen bekijken/opzoeken/toevoegen/bewerken (Youssef)
- [x] Er moet een sociaal aspect aanwezig zijn (**Roberto**)
- [x] AJAX gebruiken (**Jannick**)
- [x] Form validity (**Jannick**)
- [x] CSS + Responsive Design (**Jannick**)
- [x] HTML5 features gebruiken (**Jannick**)
- [x] Web Services (**Jannick**)
- [x] API ter beschikking stellen (**Jannick**)
- [x] Google Maps (**Jannick**)
- [x] Conclusie voor het rapport (**Roberto**)
- [x] Print-screens om mee te geven (**Roberto**)

**Comment by jhemelhof** [comment]
Heb gewoon al mijn naam bij wat dingen gezet die ik zeker kan schrijven. Als iemand anders ze echter wil doen, geen probleem ;)

**Comment by gogobetto** [comment]
Is goed voor mij :) Ik begin er morgen vroeg aan :)

**Comment by jhemelhof** [comment]
LaTeX report is nu op de repository, heb snel wat in elkaar gestoken dus pas maar aan indien nodig ;)

**Comment by YoussefBoudiba** [comment]
Is sharelatex niet handiger? https://www.sharelatex.com/

**Comment by jhemelhof** [comment]
Heb niet echt zin om te betalen om een rapport te schrijven =P

**Comment by YoussefBoudiba** [comment]
Post hier jullie e-mail adres aub

**Comment by jhemelhof** [comment]
clone1612@me.com

**Comment by gogobetto** [comment]
rj.ristuccia@gmail.com

**Comment by YoussefBoudiba** [comment]
nvm, tegen 21 u zal ik mijn tekst uploaden , jannick zou jij het dan snel herlezen aub?

**Comment by jhemelhof** [comment]
komt in orde, dus jij doet dan die 2 user dingen? Juist om zeker te zijn dat ik niet de rest (ajax, css, etc.) voor niets schrijf =P

**Comment by YoussefBoudiba** [comment]
Ik doe:
- User kan zich registreren/inloggen
- User kan dingen bekijken/(opzoeken zou jij dat doen sinds ge dat zelf hebt geïmplementeerd)/toevoegen/bewerken (Youssef)

**Comment by gogobetto** [comment]
Ik ga nu naar de bib, als ik terug kom (rond 20u) rond ik mijn deel af, kan iemand mss gewoon de technische gedeelte van edit user doen want ik kan niet goed dingen uitleggen int engels en ik wil wel dan iets anders doen in de plaats

**Comment by jhemelhof** [comment]
Wie upload er dan het project op pointcarre?

**Comment by gogobetto** [comment]
Ik wil het wel doen :)

**Comment by gogobetto** [comment]
deadline is 23:59 ?  indien ja, dan doe ik het wel als het oké voor jullie is :)

**Comment by jhemelhof** [comment]
Is goed voor mij

**Comment by YoussefBoudiba** [comment]
Ok

**Comment by YoussefBoudiba** [comment]
Check is of dat genoeg is (ik denk dat ik alles heb verteld, zonder te veel details + check mijn zinnen ; schrijven was nooit mijn ding xp). Ik moet binnen uur vertrekken btw :p

**Comment by gogobetto** [comment]
Ik zie niet wat je gedaan heb :s

**Comment by YoussefBoudiba** [comment]
check de commits

**Comment by YoussefBoudiba** [comment]
ik had geen idee waar ik het moest steken

**Comment by YoussefBoudiba** [comment]
kmoet binnen 50 min weg, dus aub snel checken :s

**Comment by jhemelhof** [comment]
Is genoeg :+1:

**Comment by gogobetto** [comment]
Wat moet er nog gedaan worden? Is het normaal dat wanneer ik pull niks nieuws binne krijg?

**Comment by YoussefBoudiba** [comment]
zeker, dan kan ik nu al vertrekken.

**Comment by jhemelhof** [comment]
Zeker ;) En heb je een al een git pull --rebase gedaan?

**Comment by gogobetto** [comment]
ik ga het proberen

**Comment by gogobetto** [comment]
k'snap het nu ik keek in de pdf file, maar eigenlijk de aanpassingen zijn in de latex file gedaan

**Comment by jhemelhof** [comment]
Wat er dan nog moet gebeuren: jouw andere delen op de git zetten, dan lees ik alles na en zet het definitieve rapport op git. Dan alles samenzetten, zippen en dan kunnen we het uploaden :)

**Comment by YoussefBoudiba** [comment]
Ok, ik ga nu vertrekken, lees goed alles na en alles dubbel checken kan geen kwaad.

**Comment by gogobetto** [comment]
Ik moet nog het sociaal aspect uitleggen

**Comment by YoussefBoudiba** [comment]
Bon, voor ik vertrek wil ik toch nog zeggen: mijn zinnen zijn soms duidelijk niet goed geformuleerd dus feel free om dat te veranderen (maar let dan wel op dat je de inhoud niet wegschrijft). Succes!

**Comment by gogobetto** [comment]
yannick, kunt ge is checken als ik dingens nog moet toevoegen? ik zie nie echt wa ik meer in de conclusie moe zette

**Comment by jhemelhof** [comment]
Ik ben nu alles aan het doornemen, zal er wel naar kijken ;)

**Comment by gogobetto** [comment]
dank u

**Comment by jhemelhof** [comment]
Alles nagelezen en alles op GIT gezet. Klaar voor indienen zou ik zeggen. Kan je de zip maken en hem doorsturen naar clone1612@me.com? Zo kan ik alles nog een laatste keer nakijken

**Comment by gogobetto** [comment]
doe ik nu :)

**Comment by gogobetto** [comment]
send :D

2015-12-23 22:27 GMT+01:00 Jannick Hemelhof notifications@github.com:

**Comment by jhemelhof** [comment]
Ik zal het idd wel posten op Pointcarré ;)

**Comment by gogobetto** [comment]
thanks :) het was fijn om met jullie aan deze project te werken en als ik jullie niemeer zie tijdens de blok fijne kerst en nieuwjaar en succes met den blok :+1:

**Comment by jhemelhof** [comment]
HET STAAT EROP :dancers:

**Comment by jhemelhof** [comment]
En inderdaad, een zeer leuk project. Voor jullie hetzelfde gewenst!

**Comment by YoussefBoudiba** [comment]
:+1:
