### ISSUE TITLE
Verslag indienen

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#14]
Het verslag moet ingediend worden in een .zip file met naam WIS­_[team_name].zip
Wij hebben als team_name 7 dus voor ons is het **WIS-Team_7.zip**

Kwa structuur moet het er zo uitzien

```
WIS-Team_7.zip
-- Code (Copy/Paste alles van de GIT hierin zonder de Report map natuurlijk)
-- Report.pdf (van ShareLatex)
-- Screenshots
---- Login.png
---- Signup.png
---- ...
```

**Comment by gogobetto** [comment]
Moeten de screenshots niet in het verslag zijn?  En de report.pdf das toch
het document van op git nee?
Le 23 déc. 2015 18:28, "Jannick Hemelhof" notifications@github.com a
écrit :

**Comment by jhemelhof** [comment]
Nee in een aparte map, zo staat het in de opgave. En zal idd de report op de git zetten als ik hem volledig hem nagekeken, maar dacht dat Youssef u ook de link van ShareLatex had doorgestuurd?

**Comment by jhemelhof** [comment]
btw zeg wanneer jullie deel van het verslag af is hier in de issue tracker, dan krijg ik een melding als ik even een power nap aan het doen ben =P

**Comment by gogobetto** [comment]
Nee geen link gekregen voor shareLatex ok is goed had ik niet gezien in de
opgave
Le 23 déc. 2015 18:54, "Jannick Hemelhof" notifications@github.com a
écrit :

**Comment by YoussefBoudiba** [comment]
sharelatex werkt enkel met 2 persoon max :/
