### ISSUE TITLE
Verwijderen van een Sighting

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#3]
Een user die is ingelogd moet in staat kunnen zijn om **zijn** sightings te verwijderen.

**Comment by YoussefBoudiba** [comment]
Waar moet dat gebeuren? Op de profiel pagina (liefst) of op de sightings pagina?

**Comment by jhemelhof** [comment]
Profielpagina lijkt mij het meest logische, idem voor bewerken
