### ISSUE TITLE
Gebruik maken van Google Maps

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#5]
We moeten gebruik maken van de Google Maps API

**Comment by jhemelhof** [comment]
Om het overzichtelijk te houden zou een user die meer info wilt over een sighting op een specifieke pagina moeten terechtkomen waar alles van die specifieke sighting staat: info, maps, weer & comments.

Doe jij dat @YoussefBoudiba of doe ik het?

**Comment by YoussefBoudiba** [comment]
Ok zal ik ook doen. Dus een pagina die algemene info geeft over alle sightings (de huidige sightings pagina) en dan een andere pagina die alle 'details" weergeeft met alle comments (een nieuwe sightings/sighting pagina)?

**Comment by jhemelhof** [comment]
Inderdaad, dus een nieuwe pagina sightings/{specifieke sighting} met alle details. Want google maps/weer neemt toch wat plaats in.

**Comment by YoussefBoudiba** [comment]
ok

**Comment by YoussefBoudiba** [comment]
Pagina is er nu nog google map integreren

**Comment by jhemelhof** [comment]
Google Maps wordt nu netjes weergegeven op de sighting page, coördinaten opgehaald van de specifieke sighting natuurlijk, en ja kan nu coördinaten meegeven bij het maken van een nieuwe sighting. 

Ik denk echter aan een nieuwe pagina (ja, alweer =P ) specifiek voor het aanmaken van een nieuwe sighting. Waarom? Omdat een user natuurlijk gewoon een naam wilt ingeven die dan op google maps wordt weergegeven, maar als ik nog een map ook in dat vakje zet wordt het wel heel druk. Wat denk jij?

**Comment by YoussefBoudiba** [comment]
"Omdat een user natuurlijk gewoon een naam wilt ingeven die dan op google maps wordt weergegeven" hoe bedoel je? Ik kan de form veranderen naar een "popupform" (modal). Dit neem dan sowieso de nodige plaats in. Verder ik denk niet dat een aparte pagina nuttig kan zijn. Als je vergelijk met facebook twitter etc. gebeurt het posten van nieuwe tweets op dezelfde pagina..

**Comment by YoussefBoudiba** [comment]
btw created by is niet nodig..

**Comment by jhemelhof** [comment]
Bedoel een adres, dus ipv coördinaten voert hij dan "Pleinlaan 9, Etterbeek" in en dan vraag ik daarvan de coördinaten op om op te slaan in de sightings.

Maar je hebt gelijk over die aparte pagina, dat is idd niet nodig. Zal het dus toevoegen aan de sightings page.

Wat bedoel je trouwens met _created by is niet nodig_ , denk niet dat ik zoiets gebruik in mijn code.

**Comment by YoussefBoudiba** [comment]
/**
- Created by Jannick on 3/12/15.
  */
  Dat bedoel ik. Sins we toch met elkaars code bezig zijn heeft dat geen nut.

**Comment by YoussefBoudiba** [comment]
"Bedoel een adres, dus ipv coördinaten voert hij dan "Pleinlaan 9, Etterbeek" in en dan vraag ik daarvan de coördinaten op om op te slaan in de sightings." Dat kan super user friendly zijn. Heb de google map api nog niet bekeken. nadat ik comments heb afgewerkt zal ik er naar kijken, ma voorlopig werkt google map goed ;)

**Comment by jhemelhof** [comment]
Ik ben bijna klaar met dat adres, user friendly ftw ;) En die created by is iets wat mijn IDE automatisch aanmaakte, lette er niet echt op. Zal het aanpassen.

**Comment by YoussefBoudiba** [comment]
ok, comment zal ik afkrijgen tegen vanavond. dan hebben we alles neem ik aan?

**Comment by jhemelhof** [comment]
Wel er staan nog wat issues open (verwijderen/updaten van een sighting, profiel, ...) dus we hebben nog niet alles

**Comment by YoussefBoudiba** [comment]
verwijderen en updaten doe ik wel

**Comment by jhemelhof** [comment]
Ok, laatste deel voor Google Maps staat er nu op: bij het aanmaken van een nieuwe sighting kan de user gewoon een adres opgeven en dit tonen op de kaart door op **Preview Location** te klikken. De coördinaten worden dan automatisch ingevuld en de map wordt getoond samen met een marker voor de location.

Test het misschien eens en weet mij te zeggen wat er nog eventueel aangepast moet worden.

**Comment by YoussefBoudiba** [comment]
ok zal ik nu doen

**Comment by YoussefBoudiba** [comment]
kleine bug, preview werkt maar gaat automatische een niew sighting posten.

**Comment by YoussefBoudiba** [comment]
Wat doet $scope.$digest() ?

**Comment by jhemelhof** [comment]
$digest vraagt om de view met ajax te refreshen, omdat ik in de geoCoder zit worden de values in de $scope anders niet automatisch aangepast

**Comment by YoussefBoudiba** [comment]
heb je de bug ondertussen al kunnen waarnemen? Dus als je de velden title en description heb ingevuld en vervolgens op preview klikt wordt de sighting automatisch gepost. Ik ben zeker dat digest hiermee iets te maken heeft.

**Comment by YoussefBoudiba** [comment]
trouwens ge kunt de values aanpassen door $scope.variable = newvalue

**Comment by YoussefBoudiba** [comment]
en trouwens waarom komen mijn commits niet op git?

**Comment by jhemelhof** [comment]
Weet ik, maar zonder de digest verandert er niets op de view. Probeer het nu op te lossen :) Geen idee waarom uw commits er niet opkomen, heb je al een **git pull --rebase** gedaan gevolgd door een **git push** ?

**Comment by jhemelhof** [comment]
Hmm, zelfs zonder die digest() wordt er nog een nieuwe sighting aangemaakt. Zie niet waardoor het zou kunnen komen

**Comment by YoussefBoudiba** [comment]
Zal er naar kijken, ga nu wel gaan eten. Test de nieuwe comment feature :p tis nog basic ma het werkt

**Comment by YoussefBoudiba** [comment]
ik moet ook nog rekening houden met ingelogde user etc. ma dat doe ik binnen een uur of twee. En ik ga al beginnen met de code "op te kuisen".

**Comment by jhemelhof** [comment]
Opgelost! Lag aan de button zelf, blijkbaar als ik geen type meegeef met <button> is het default een submit dus hij voerde mijn code uit en daarna submitte hij het form. 

Comments lijken precies niet te werken, wanneer ik op Add a comment klik krijg ik een venster met _retirn_

**Comment by YoussefBoudiba** [comment]
heb je de laatste versie gepulled?

**Comment by jhemelhof** [comment]
Aha dat was het, dacht dat ik up to date was maar nee. Nu werkt het wel, ziet er clean uit, geen bugs :+1: 

Mijn fix staat er nu ook op.

**Comment by YoussefBoudiba** [comment]
ok ga het pullen

**Comment by YoussefBoudiba** [comment]
Ok ik ga nu gaan eten :p Binnen een uur zal ik nog werken aan de comments (code updaten, enkel ingelogde users kunnen comment posten,...). Wil je trouwens een popupform om niewe sighting te posten?

**Comment by jhemelhof** [comment]
:+1: 

Popupform zou er wel cleaner uitzien =P

**Comment by YoussefBoudiba** [comment]
ok

**Comment by YoussefBoudiba** [comment]
Popup is er nu :) en enkel ingelogde user kunnen comments toevoegen. Comments is nu af denk ik?

**Comment by jhemelhof** [comment]
Ziet er zeer netjes uit :) Lijkt er wel op dat je geen comments kan schrijven op de sighting page zelf?

**Comment by YoussefBoudiba** [comment]
Yup, zal het later nog toevoegen. Moet er nog andere zaken bij of is het 'af'?

**Comment by jhemelhof** [comment]
OK, er moet voor mij niets meer bij :+1:

**Comment by YoussefBoudiba** [comment]
Voila t'is geimplementeerd :)

**Comment by jhemelhof** [comment]
Netjes, zeer netjes :) Ik sluit deze issue nu want we wijken wel een beetje af van Google Maps =P
