### ISSUE TITLE
Gebruik maken van externe API

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#7]
We moeten voor het project gebruik maken van een externe API. Locatie linken aan het weer lijkt de meest logische oplossing.

**Comment by YoussefBoudiba** [comment]
Ik ben nu bezig met imgur api door te nemen om images op te slaan. Is dat niet gebruik maken van een externe API?

**Comment by jhemelhof** [comment]
Dat is idd een externe api, het gaat er wel om dat we data van een externe service halen met een get request dus indien we daar aan voldoen is het in orde.

Had ook al eens de imgur api doorgenomen, ziet er nog redelijk eenvoudig uit.

**Comment by jhemelhof** [comment]
Heb support voor imgur toegevoegd door een service te schrijven in 945053102f1f2245bb776b3a28df0c1c97dc1a51

Op dit moment is er maar ondersteuning voor 1 endpoint (ophalen van images met een bepaalde tag) om zo aan de requirement te voldoen, maar dit kan zeer makkelijk worden uitgebreid met andere endpoints.

**Comment by YoussefBoudiba** [comment]
Hou je hiermee bezig of moet ik dat doen?

**Comment by jhemelhof** [comment]
Ik zal het wel doen, zeg gewoon welke endpoints van de api jullie nodig hebben en dan implementeer ik ze wel

**Comment by YoussefBoudiba** [comment]
Zolang je images kan opslaan en terugvinden via id of url is het goed. Dus een user kies een bestand op zijn pc, stuurt het naar imgur. Hierna kan eendert welk user de foto terug vinden op de view pagina van de sighting.

**Comment by jhemelhof** [comment]
Je kan nu images uploaden naar imgur, er staat er voorbeeld in homeCtrl.js

Als resultaat van het uploaden komt er dus een antwoord in de vorm van JSON, waardoor we dus makkelijk aan de url van de image kunnen geraken (staat ok in vb). Dus user kiest bestand, uploaden en dan `$scope.url = result.data.link` om de url van de sighting juist te zetten.

**Comment by YoussefBoudiba** [comment]
Kun je dat snel toevoegen in "new sighting"? Dus een user kiest een foto op zijn pc (geen url, het is niet de bedoeling van onze app) en achter het scherm wordt een image object gecrreerd die de id van de sighting bevat. dat wordt allemaal opgeslagen in db. wanneer de user op view klikt wordt in db een findOne querie gestart met als parameter de sighting id. en wordt dat via imgur api op het scherm weergegeven.

**Comment by jhemelhof** [comment]
Zal eens zien, zou wel moeten lukken

**Comment by jhemelhof** [comment]
De code is er, maar er loopt toch iets fout met het doorgeven van de base64 string naar imgur. Hij lijkt te worden geweigerd. Zal er morgen nog wel eens naar kijken

**Comment by jhemelhof** [comment]
Fouten opgelost in laatste commit + image op home page zal nu niet meer zo groot zijn =P
