### ISSUE TITLE
HTML5 gebruiken

### ISSUE THREAD

**Issue by jhemelhof** [WIS7/ufoTracker#8]
We moeten gebruik maken van minstens drie features die werden geïntroduceerd met HTML5:
- [x] Local Storage
- [x] Date picker/Validator
- [x] Geolocation

**Comment by jhemelhof** [comment]
We moeten nog beslissen wat onze derde feature van html5 wordt @YoussefBoudiba @gogobetto

**Comment by YoussefBoudiba** [comment]
date picker wordt niet ondersteund in mozilla en ie :/

**Comment by jhemelhof** [comment]
Dan maar validators van html5 gebruiken
