### ISSUE TITLE
Profiel pagina

### ISSUE THREAD

**Issue by YoussefBoudiba** [WIS7/ufoTracker#9]
Eerst de 'profile' template vervolledigen met alles wat er in moet (user info, zijn sightings, comments, etc). Nog geen communicatie met server en db nodig, maar wel username kunnen tonen zoals het nu ook het geval is en voorlopig werken met dummy data. Hierna als alles werkt vervolledigen met communicatie..

**Comment by YoussefBoudiba** [comment]
@gogobetto zou jij dat willen doen?

**Comment by YoussefBoudiba** [comment]
req:
1. Lijst van zijn eigen sightings kunnen weergeven (hierna editen/delten)
2. Info kunnen weergeven van de user (editen/delte profile).
3. ...
4 \* search user (username and sightings)

**Comment by gogobetto** [comment]
Done, Jannick check dat jouw zoekfunctie nog altijd werkt met users.
